name: mydotnet project

on:
  push:
    branches:
      - develop

jobs:
  dotnet_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.100'

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
        with:
          args: >
            -Dsonar.organization=pavan01234567
            -Dsonar.projectKey=pavan01234567_nopCommerce

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: ECR login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag & Push Docker Image
        run: |
          docker build -t dotnetapp:1.0 .
          docker tag dotnetapp:1.0 000373574701.dkr.ecr.ap-south-1.amazonaws.com/petclinic/app:latest
          docker push 000373574701.dkr.ecr.ap-south-1.amazonaws.com/petclinic/app:latest

      - name: Setup kubectl
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

      - name: Apply Kubernetes Manifests
        run: |
          kubectl apply -f .
          kubectl get pods
